"""
services/rag/chunking.py
========================
Deterministic document text chunking with page and boundary preservation.

Features:
- Configurable chunk size and overlap
- Page number tracking based on form feeds, OCR headers, or page delimiters
- Paragraph and sentence boundary awareness
- Whitespace normalization and empty chunk skipping
- Token count estimation
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger("app.services.rag.chunking")

# Common patterns matching page delimiters generated by OCR and PDF extractors
PAGE_DELIMITER_PATTERNS = [
    re.compile(r"(?:^|\n)(?:[-=]{3,}\s*(?:Page|PAGE)\s*(\d+)\s*[-=]{3,})", re.IGNORECASE),
    re.compile(r"(?:^|\n)(?:\[(?:Page|PAGE)\s*(\d+)\])", re.IGNORECASE),
    re.compile(r"\x0c"),  # Standard Form Feed character
]


@dataclass
class TextChunk:
    """Represents a segmented portion of a document's text."""
    chunk_index: int
    content: str
    page_number: int | None
    token_count: int
    metadata: dict[str, Any] = field(default_factory=dict)


def normalize_text(text: str) -> str:
    """Normalize excessive whitespace while preserving paragraphs."""
    if not text:
        return ""
    # Normalize Windows line breaks
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Replace tabs with spaces
    text = text.replace("\t", " ")
    # Collapse 3+ newlines to 2
    text = re.sub(r"\n{3,}", "\n\n", text)
    # Collapse multiple consecutive inline spaces
    lines = [re.sub(r" {2,}", " ", line).strip() for line in text.split("\n")]
    return "\n".join(lines).strip()


def estimate_token_count(text: str) -> int:
    """
    Estimate token count based on standard English heuristics
    (~4 characters per token or 1.3 tokens per word).
    """
    if not text:
        return 0
    words = len(text.split())
    by_words = int(words * 1.3)
    by_chars = max(1, len(text) // 4)
    return max(1, (by_words + by_chars) // 2)


def extract_pages(text: str) -> list[tuple[int | None, str]]:
    """
    Split text into (page_number, page_text) tuples if page markers are present.
    If no page markers exist, returns [(1, text)].
    """
    if not text or not text.strip():
        return []

    # Check for form feed character \x0c
    if "\x0c" in text:
        pages: list[tuple[int | None, str]] = []
        raw_pages = text.split("\x0c")
        for idx, p in enumerate(raw_pages, start=1):
            cleaned = normalize_text(p)
            if cleaned:
                pages.append((idx, cleaned))
        if pages:
            return pages

    # Check for '--- Page X ---' or similar regex patterns
    header_pattern = re.compile(
        r"(?:^|\n)(?:[-=]{3,}\s*(?:Page|PAGE)\s*(\d+)\s*[-=]{3,}|\[(?:Page|PAGE)\s*(\d+)\])",
        re.MULTILINE,
    )
    matches = list(header_pattern.finditer(text))
    if matches:
        pages = []
        last_end = 0
        current_page_num: int | None = 1

        for match in matches:
            start, end = match.span()
            content_before = normalize_text(text[last_end:start])
            if content_before:
                pages.append((current_page_num, content_before))
            # Extract matched page number
            num_str = match.group(1) or match.group(2)
            current_page_num = int(num_str) if num_str else (pages[-1][0] + 1 if pages and pages[-1][0] else 1)
            last_end = end

        remaining = normalize_text(text[last_end:])
        if remaining:
            pages.append((current_page_num, remaining))

        if pages:
            return pages

    # Fallback: single document block
    normalized = normalize_text(text)
    return [(1, normalized)] if normalized else []


def split_text_into_chunks(
    text: str,
    chunk_size: int,
    chunk_overlap: int,
    page_number: int | None = None,
    start_index: int = 0,
    metadata: dict[str, Any] | None = None,
) -> list[TextChunk]:
    """
    Deterministically segment text into overlapping chunks respecting paragraph/sentence boundaries.
    """
    if not text or not text.strip():
        return []

    meta = metadata or {}
    chunks: list[TextChunk] = []

    # If text is already smaller than chunk_size, return single chunk
    if len(text) <= chunk_size:
        token_cnt = estimate_token_count(text)
        return [
            TextChunk(
                chunk_index=start_index,
                content=text,
                page_number=page_number,
                token_count=token_cnt,
                metadata={**meta, "start_char": 0, "end_char": len(text)},
            )
        ]

    # Split into paragraphs or line blocks first
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    if not paragraphs:
        paragraphs = [text]

    current_chunk: list[str] = []
    current_length = 0
    chunk_counter = start_index

    for para in paragraphs:
        # If single paragraph exceeds chunk_size, split by sentences or sliding window
        if len(para) > chunk_size:
            # Flush existing chunk before processing large paragraph
            if current_chunk:
                chunk_str = "\n\n".join(current_chunk).strip()
                if chunk_str:
                    chunks.append(
                        TextChunk(
                            chunk_index=chunk_counter,
                            content=chunk_str,
                            page_number=page_number,
                            token_count=estimate_token_count(chunk_str),
                            metadata={**meta},
                        )
                    )
                    chunk_counter += 1
                current_chunk = []
                current_length = 0

            # Split large paragraph by sentences
            sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", para) if s.strip()]
            if len(sentences) <= 1 and len(para) > chunk_size:
                # Fallback to word-level units if no punctuation boundaries exist
                sentences = [w for w in para.split(" ") if w]
            sub_chunk: list[str] = []
            sub_len = 0

            for sentence in sentences:
                if sub_len + len(sentence) + 1 > chunk_size and sub_chunk:
                    sub_str = " ".join(sub_chunk).strip()
                    if sub_str:
                        chunks.append(
                            TextChunk(
                                chunk_index=chunk_counter,
                                content=sub_str,
                                page_number=page_number,
                                token_count=estimate_token_count(sub_str),
                                metadata={**meta},
                            )
                        )
                        chunk_counter += 1
                    # Overlap: keep trailing words/sentence up to chunk_overlap
                    overlap_chars = sub_str[-chunk_overlap:] if len(sub_str) > chunk_overlap else sub_str
                    sub_chunk = [overlap_chars, sentence]
                    sub_len = len(overlap_chars) + len(sentence) + 1
                else:
                    sub_chunk.append(sentence)
                    sub_len += len(sentence) + 1

            if sub_chunk:
                remaining_sub = " ".join(sub_chunk).strip()
                if remaining_sub:
                    current_chunk = [remaining_sub]
                    current_length = len(remaining_sub)
            continue

        # Standard paragraph accumulation
        if current_length + len(para) + 2 > chunk_size and current_chunk:
            chunk_str = "\n\n".join(current_chunk).strip()
            if chunk_str:
                chunks.append(
                    TextChunk(
                        chunk_index=chunk_counter,
                        content=chunk_str,
                        page_number=page_number,
                        token_count=estimate_token_count(chunk_str),
                        metadata={**meta},
                    )
                )
                chunk_counter += 1

            # Build overlap from the end of the previous chunk
            overlap_prefix = chunk_str[-chunk_overlap:] if len(chunk_str) > chunk_overlap else ""
            if overlap_prefix:
                current_chunk = [overlap_prefix, para]
                current_length = len(overlap_prefix) + len(para) + 2
            else:
                current_chunk = [para]
                current_length = len(para)
        else:
            current_chunk.append(para)
            current_length += len(para) + 2

    # Flush remaining text
    if current_chunk:
        chunk_str = "\n\n".join(current_chunk).strip()
        if chunk_str and len(chunk_str) >= 15:  # Avoid trailing micro-fragments
            chunks.append(
                TextChunk(
                    chunk_index=chunk_counter,
                    content=chunk_str,
                    page_number=page_number,
                    token_count=estimate_token_count(chunk_str),
                    metadata={**meta},
                )
            )
        elif chunk_str and chunks:
            # Append tiny fragment to previous chunk if acceptable
            prev = chunks[-1]
            merged_content = prev.content + "\n\n" + chunk_str
            chunks[-1] = TextChunk(
                chunk_index=prev.chunk_index,
                content=merged_content,
                page_number=prev.page_number,
                token_count=estimate_token_count(merged_content),
                metadata=prev.metadata,
            )

    return chunks


def chunk_document_text(
    text: str,
    document_metadata: dict[str, Any] | None = None,
    chunk_size: int | None = None,
    chunk_overlap: int | None = None,
) -> list[TextChunk]:
    """
    Main entry point for chunking full document text.

    Preserves page boundaries when present, chunks each page with overlap,
    and returns a flattened list of TextChunk objects with strictly continuous chunk_index.
    """
    if not text or not text.strip():
        return []

    size = chunk_size or settings.RAG_CHUNK_SIZE
    overlap = chunk_overlap or settings.RAG_CHUNK_OVERLAP
    meta = document_metadata or {}

    pages = extract_pages(text)
    all_chunks: list[TextChunk] = []
    global_index = 0

    for page_num, page_text in pages:
        page_chunks = split_text_into_chunks(
            text=page_text,
            chunk_size=size,
            chunk_overlap=overlap,
            page_number=page_num,
            start_index=global_index,
            metadata={**meta, "page_number": page_num},
        )
        for chk in page_chunks:
            chk.chunk_index = global_index
            all_chunks.append(chk)
            global_index += 1

    return all_chunks


def chunk_text(
    text: str,
    chunk_size: int | None = None,
    chunk_overlap: int | None = None,
    metadata: dict[str, Any] | None = None,
) -> list[TextChunk]:
    """Convenience alias for deterministic text chunking."""
    size = chunk_size or settings.RAG_CHUNK_SIZE
    overlap = chunk_overlap or settings.RAG_CHUNK_OVERLAP
    return split_text_into_chunks(text, chunk_size=size, chunk_overlap=overlap, metadata=metadata)


split_into_pages = extract_pages

