"""
agents/classification/schemas.py
================================
Pydantic schemas for the Classification Agent output.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from app.core.enums import DocumentType


class DocumentClassification(BaseModel):
    """
    Structured classification result generated by the Classification Agent.
    """

    document_type: DocumentType = Field(
        description="Classified document category: INVOICE, RECEIPT, PURCHASE_ORDER, CONTRACT, or OTHER.",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 indicating model certainty.",
    )
    reasoning: str = Field(
        description="Concise rationale explaining the evidence for this classification.",
    )
    signals: list[str] = Field(
        default_factory=list,
        description="Specific textual or structural features detected in the document.",
    )
